/**
 * Name-day model for /namnsdag/ (Swedish almanac only).
 * Data: src/data/namnsdagar.ts, generated by scripts/gen-namnsdagar.mjs
 * from the Födelsedagar app, so the site and the app agree.
 */
import { NAMNSDAGAR, TILLAGG_2027 } from '../data/namnsdagar';
import { MANADER, mdKey, type YMD } from './datum';

export { NAMNSDAGAR, TILLAGG_2027 };

/** First year the Isof additions appear in the almanac. */
export const TILLAGG_FRAN_AR = 2027;

/** Days that have no name in the Swedish almanac, and why. */
export const NAMNLOSA_DAGAR: Record<string, string> = {
  '01-01': 'Nyårsdagen',
  '02-02': 'Kyndelsmässodagen',
  '02-29': 'Skottdagen',
  '03-25': 'Marie bebådelsedag',
  '06-24': 'Johannes Döparens dag',
  '11-01': 'Allhelgonadagen',
  '12-25': 'Juldagen',
};

/** Names celebrated on a date. The 2027 additions only count from 2027. */
export function namesOn(date: YMD): string[] {
  const k = mdKey(date);
  const base = NAMNSDAGAR[k] ?? [];
  if (date.y >= TILLAGG_FRAN_AR && TILLAGG_2027[k]) return [...base, ...TILLAGG_2027[k]];
  return base;
}

/** Names for a 'MM-DD' key regardless of year: base names plus the 2027
 *  additions (flagged), for the year-independent month tables. */
export function namesForKey(key: string): { name: string; from2027: boolean }[] {
  return [
    ...(NAMNSDAGAR[key] ?? []).map((name) => ({ name, from2027: false })),
    ...(TILLAGG_2027[key] ?? []).map((name) => ({ name, from2027: true })),
  ];
}

export interface NameEntry {
  name: string;
  slug: string;
  /** 'MM-DD' */
  key: string;
  m: number;
  d: number;
  from2027: boolean;
}

const TRANSLIT: Record<string, string> = { å: 'aa', ä: 'ae', ö: 'oe' };

/** "Åsa" → "asa", "Gustav Adolf" → "gustav-adolf". */
export function slugifyName(name: string, strictSwedish = false): string {
  let s = name.toLowerCase();
  if (strictSwedish) s = s.replace(/[åäö]/g, (c) => TRANSLIT[c]);
  return s
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function buildNames(): NameEntry[] {
  const raw: Omit<NameEntry, 'slug'>[] = [];
  const push = (table: Record<string, string[]>, from2027: boolean) => {
    for (const [key, names] of Object.entries(table)) {
      const [m, d] = key.split('-').map(Number);
      for (const name of names) raw.push({ name, key, m, d, from2027 });
    }
  };
  push(NAMNSDAGAR, false);
  push(TILLAGG_2027, true);

  // Collisions (Marit/Märit, Marta/Märta): the plain spelling keeps the
  // simple slug, the one with å/ä/ö gets "ae"/"aa"/"oe".
  const count: Record<string, number> = {};
  for (const r of raw) {
    const s = slugifyName(r.name);
    count[s] = (count[s] ?? 0) + 1;
  }
  const out = raw.map((r) => {
    const simple = slugifyName(r.name);
    const clash = count[simple] > 1 && /[åäö]/i.test(r.name);
    return { ...r, slug: clash ? slugifyName(r.name, true) : simple };
  });
  const seen = new Set<string>();
  for (const e of out) {
    if (seen.has(e.slug)) throw new Error(`Duplicate name-day slug: ${e.slug}`);
    seen.add(e.slug);
  }
  return out.sort((a, b) => a.name.localeCompare(b.name, 'sv'));
}

export const NAMES: NameEntry[] = buildNames();
export const NAME_BY_NAME: Record<string, NameEntry> = Object.fromEntries(
  NAMES.map((n) => [n.name, n]),
);

export const nameUrl = (name: string) => `/namnsdag/namn/${NAME_BY_NAME[name].slug}/`;
export const monthUrl = (m: number) => `/namnsdag/${MANADER[m - 1]}/`;

export const SOURCE_URL =
  'https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_namnsdagar_i_Sverige_i_datumordning';
